### ISSUE TITLE
new user question

### ISSUE THREAD

**Issue by joesloan** [dpwe/audfprint#12]
Hi,

To see if I had installed correctly. I ran "new" and then "match" on the same sample mp3 file. However match ran for a few minutes  and then "Terminated".

I can't tell if that error matters.

Would appreciate any help. Apologies if I am doing something wrong.

Is there a post-install reference check I can do to see if my install is ok?

python audfprint.py new -d animals2 references/280.mp3
/usr/local/lib/python2.7/dist-packages/librosa/core/audio.py:33: UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
  warnings.warn('Could not import scikits.samplerate. '
Thu Oct 15 07:42:13 2015 ingesting #0: references/280.mp3 ...
Added 162 hashes (16.7 hashes/sec)
Processed 1 files (9.7 s total dur) in 8.9 s sec = 0.913 x RT
Saved fprints for 1 files ( 162 hashes) to animals2
Dropped hashes= 0 (0.00%)
root@ubuntu:~/freetype-2.5.3/audfprint-master# python audfprint.py match -d animals2 references/280.mp3
/usr/local/lib/python2.7/dist-packages/librosa/core/audio.py:33: UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
  warnings.warn('Could not import scikits.samplerate. '
Thu Oct 15 07:43:08 2015 Reading hash table animals2
Terminated

**Comment by dpwe** [comment]
This looks very weird to me. Can you send me the mp3 ?

  DAn.

**Comment by joesloan** [comment]
Hi Dan,

I just picked this one at random...

http://www.noiseaddicts.com/samples_1w72b820/280.mp3

Maybe it is a bad example to use?

Joe

On 15 October 2015 at 14:28, Dan Ellis <notifications@github.com> wrote:

> This looks very weird to me. Can you send me the mp3 ?
>
> DAn.
>
> On Thursday, October 15, 2015, joesloan <notifications@github.com> wrote:
>
> > Hi,
> >
> > To see if I had installed correctly. I ran "new" and then "match" on the
> > same sample mp3 file. However match ran for a few minutes and then
> > "Terminated".
> >
> > I can't tell if that error matters.
> >
> > Would appreciate any help. Apologies if I am doing something wrong.
> >
> > Is there a post-install reference check I can do to see if my install is
> > ok?
> >
> > python audfprint.py new -d animals2 references/280.mp3
> > /usr/local/lib/python2.7/dist-packages/librosa/core/audio.py:33:
> > UserWarning: Could not import scikits.samplerate. Falling back to
> > scipy.signal
> > warnings.warn('Could not import scikits.samplerate. '
> > Thu Oct 15 07:42:13 2015 ingesting #0: references/280.mp3 ...
> > Added 162 hashes (16.7 hashes/sec)
> > Processed 1 files (9.7 s total dur) in 8.9 s sec = 0.913 x RT
> > Saved fprints for 1 files ( 162 hashes) to animals2
> > Dropped hashes= 0 (0.00%)
> > root@ubuntu:~/freetype-2.5.3/audfprint-master# python audfprint.py match
> > -d animals2 references/280.mp3
> > /usr/local/lib/python2.7/dist-packages/librosa/core/audio.py:33:
> > UserWarning: Could not import scikits.samplerate. Falling back to
> > scipy.signal
> > warnings.warn('Could not import scikits.samplerate. '
> > Thu Oct 15 07:43:08 2015 Reading hash table animals2
> > Terminated
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dpwe/audfprint/issues/12>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpwe/audfprint/issues/12#issuecomment-148385687>.
>



-- 
Joe Sloan
Deoca Ltd,
Dublin, Ireland

mobile: +353872740776
skype:  joesloan
email: joe.sloan@deoca.com

**Comment by dpwe** [comment]
Sooo ...

It works on my macbook:

dpwe@dpwe-macbookpro2:~/Downloads/audfprint-master$ python
audfprint.py new -d animals2 ../280.mp3
/Users/dpwe/homebrew/lib/python2.7/site-packages/librosa-0.4.0rc2-py2.7.egg/librosa/core/audio.py:34:
UserWarning: Could not import scikits.samplerate. Falling back to
scipy.signal
Thu Oct 15 11:27:13 2015 ingesting #0: ../280.mp3 ...
Added 178 hashes (18.4 hashes/sec)
Processed 1 files (9.7 s total dur) in 0.1 s sec = 0.015 x RT
Saved fprints for 1 files ( 178 hashes) to animals2
dpwe@dpwe-macbookpro2:~/Downloads/audfprint-master$ python
audfprint.py match -d animals2 ../280.mp3
/Users/dpwe/homebrew/lib/python2.7/site-packages/librosa-0.4.0rc2-py2.7.egg/librosa/core/audio.py:34:
UserWarning: Could not import scikits.samplerate. Falling back to
scipy.signal
Read fprints for 1 files ( 178 hashes) from animals2
Analyzed ../280.mp3 of 9.125 s to 614 hashes
Matched ../280.mp3 9.125 sec 614 raw hashes as ../280.mp3 at 0.023 s
with 198 of 198 hashes
Processed 1 files (9.7 s total dur) in 0.2 s sec = 0.022 x RT
dpwe@dpwe-macbookpro2:~/Downloads/audfprint-master$

"Terminated" sounds like something really dire like Out Of Memory
killer.  It looks like maybe it's trying to use ~1GB of core with a
few glances at Top.

Maybe try

python audfprint.py new -d animals2 --bucketsize 20 ../280.mp3

.. which should reduce the memory usage to ~20% and see if that helps?

   DAn.

**Comment by joesloan** [comment]
Thanks will try that tomorrow, also will try on bigger server container.

**Comment by joesloan** [comment]
Thanks Dan,

that worked.


On 15 October 2015 at 17:14, <joe.sloan@deoca.com> wrote:

> Thanks will try that tomorrow, also will try on bigger server container.
>
> Sent from my iPad
>
> On 15 Oct 2015, at 16:32, Dan Ellis <notifications@github.com> wrote:
>
> Sooo ...
>
> It works on my macbook:
>
> dpwe@dpwe-macbookpro2:~/Downloads/audfprint-master$ python
> audfprint.py new -d animals2 ../280.mp3
>
> /Users/dpwe/homebrew/lib/python2.7/site-packages/librosa-0.4.0rc2-py2.7.egg/librosa/core/audio.py:34:
> UserWarning: Could not import scikits.samplerate. Falling back to
> scipy.signal
> Thu Oct 15 11:27:13 2015 ingesting #0: ../280.mp3 ...
> Added 178 hashes (18.4 hashes/sec)
> Processed 1 files (9.7 s total dur) in 0.1 s sec = 0.015 x RT
> Saved fprints for 1 files ( 178 hashes) to animals2
> dpwe@dpwe-macbookpro2:~/Downloads/audfprint-master$ python
> audfprint.py match -d animals2 ../280.mp3
>
> /Users/dpwe/homebrew/lib/python2.7/site-packages/librosa-0.4.0rc2-py2.7.egg/librosa/core/audio.py:34:
> UserWarning: Could not import scikits.samplerate. Falling back to
> scipy.signal
> Read fprints for 1 files ( 178 hashes) from animals2
> Analyzed ../280.mp3 of 9.125 s to 614 hashes
> Matched ../280.mp3 9.125 sec 614 raw hashes as ../280.mp3 at 0.023 s
> with 198 of 198 hashes
> Processed 1 files (9.7 s total dur) in 0.2 s sec = 0.022 x RT
> dpwe@dpwe-macbookpro2:~/Downloads/audfprint-master$
>
> "Terminated" sounds like something really dire like Out Of Memory
> killer. It looks like maybe it's trying to use ~1GB of core with a
> few glances at Top.
>
> Maybe try
>
> python audfprint.py new -d animals2 --bucketsize 20 ../280.mp3
>
> .. which should reduce the memory usage to ~20% and see if that helps?
>
> DAn.
>
> On Thu, Oct 15, 2015 at 10:16 AM, joesloan <notifications@github.com>
> wrote:
> > Hi Dan,
> >
> > I just picked this one at random...
> >
> > http://www.noiseaddicts.com/samples_1w72b820/280.mp3
> >
> > Maybe it is a bad example to use?
> >
> > Joe
> >
> > On 15 October 2015 at 14:28, Dan Ellis <notifications@github.com> wrote:
> >
> >> This looks very weird to me. Can you send me the mp3 ?
> >>
> >> DAn.
> >>
> >> On Thursday, October 15, 2015, joesloan <notifications@github.com>
> wrote:
> >>
> >> > Hi,
> >> >
> >> > To see if I had installed correctly. I ran "new" and then "match" on
> the
> >> > same sample mp3 file. However match ran for a few minutes and then
> >> > "Terminated".
> >> >
> >> > I can't tell if that error matters.
> >> >
> >> > Would appreciate any help. Apologies if I am doing something wrong.
> >> >
> >> > Is there a post-install reference check I can do to see if my install
> is
> >> > ok?
> >> >
> >> > python audfprint.py new -d animals2 references/280.mp3
> >> > /usr/local/lib/python2.7/dist-packages/librosa/core/audio.py:33:
> >> > UserWarning: Could not import scikits.samplerate. Falling back to
> >> > scipy.signal
> >> > warnings.warn('Could not import scikits.samplerate. '
> >> > Thu Oct 15 07:42:13 2015 ingesting #0: references/280.mp3 ...
> >> > Added 162 hashes (16.7 hashes/sec)
> >> > Processed 1 files (9.7 s total dur) in 8.9 s sec = 0.913 x RT
> >> > Saved fprints for 1 files ( 162 hashes) to animals2
> >> > Dropped hashes= 0 (0.00%)
> >> > root@ubuntu:~/freetype-2.5.3/audfprint-master# python audfprint.py
> match
> >> > -d animals2 references/280.mp3
> >> > /usr/local/lib/python2.7/dist-packages/librosa/core/audio.py:33:
> >> > UserWarning: Could not import scikits.samplerate. Falling back to
> >> > scipy.signal
> >> > warnings.warn('Could not import scikits.samplerate. '
> >> > Thu Oct 15 07:43:08 2015 Reading hash table animals2
> >> > Terminated
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <https://github.com/dpwe/audfprint/issues/12>.
> >> >
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/dpwe/audfprint/issues/12#issuecomment-148385687>.
> >>
> >
> >
> >
> > --
> > Joe Sloan
> > Deoca Ltd,
> > Dublin, Ireland
> >
> > mobile: +353872740776
> > skype: joesloan
> > email: joe.sloan@deoca.com
> >
> > —
> > Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpwe/audfprint/issues/12#issuecomment-148424800>.
>
>


-- 
Joe Sloan
Deoca Ltd,
Dublin, Ireland

mobile: +353872740776
skype:  joesloan
email: joe.sloan@deoca.com

**Comment by dpwe** [comment]
In summary: The code works by allocating a large in-core database.  With the default options, this is something like 400MB.  When running on machines where this is a significant fraction of available core, this may cause the process to be killed by the kernel ("Terminated.").  Try running with fewer buckets, e.g. --bucketsize 20.
