### ISSUE TITLE
Listing items in the database

### ISSUE THREAD

**Issue by joesloan** [dpwe/audfprint#13]
Hi,

Is is the any way to list the items currently in a database?

thanks

**Comment by dpwe** [comment]
It's not supported in the program at present, but it would be quite easy to
add.  I'm planning on doing some work to add the ability to remove single
items from the database, so I'll try to add this too.

  DAn.

**Comment by joesloan** [comment]
Thanks Dan,

On 21 October 2015 at 21:45, Dan Ellis <notifications@github.com> wrote:

> It's not supported in the program at present, but it would be quite easy to
> add. I'm planning on doing some work to add the ability to remove single
> items from the database, so I'll try to add this too.
>
> DAn.
>
> On Wed, Oct 21, 2015 at 3:18 PM, joesloan <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > Is is the any way to list the items currently in a database?
> >
> > thanks
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dpwe/audfprint/issues/13>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpwe/audfprint/issues/13#issuecomment-150019313>.
>



-- 
Joe Sloan
Deoca Ltd,
Dublin, Ireland

mobile: +353872740776
skype:  joesloan
email: joe.sloan@deoca.com

**Comment by dpwe** [comment]
Fixed via https://github.com/dpwe/audfprint/commit/07f764195b39642d3f0858c5897d57cddc383535

**Comment by dpwe** [comment]
I just added a list option to audfprint.

  DAn.
