### ISSUE TITLE
two little bugs?

### ISSUE THREAD

**Issue by fengliu2014** [dpwe/audfprint#19]
1, In audfprint.py line 358, it should be 
-v, --verbose                             Verbosity level
2, In audfprint_match.py line 183, it should be
results.resize((maxnresults, 7))

**Comment by dpwe** [comment]
Fenglui - 

Thanks for your comments.

> 1, In audfprint.py line 358, it should be
> -v, --verbose Verbosity level

Although the use of verbosity is only as a boolean flag at present, the idea is to support different verbosity levels by accepting an argument.  So I think this is WAI.

> 2, In audfprint_match.py line 183, it should be
> results.resize((maxnresults, 7))

I think you're referring to the line that's
```
                        results.resize((maxnresults, results.shape[1]))
```
It's true that results.shape[1] is equal to 7, but the idea is to avoid having that "magic number" show up in too many places, in case I change the number of columns in the future.  So although the existing code is inefficient, it's deliberate.

  DAn.

**Comment by fengliu2014** [comment]
Thank you DAn,
You new commit on Apr 15th fixed the 2nd bug well.
It was results.resize((maxnresults, 5)) before.
