### ISSUE TITLE
how to get audio file duration

### ISSUE THREAD

**Issue by shuvuu** [dpwe/audfprint#20]
Hello, 

How can I get/calculate file duration from database? Can I store file duration while adding to database?

I want to query long mixed/combined audio file. Original files are in database. Is it possible already?

ps: I noticed that when I re-add files to database hash size doubles but number of files same as before.

**Comment by dpwe** [comment]
The duration of the reference tracks is not stored directly.  Assuming your maxtimebits is large enough to avoid aliasing, you could estimate it by finding the largest time index of any hash associated with the reference track ID in the hash database, but this would be quite slow as you'd have to scan the entire hash table to find instances of that ID.  If you needed that value, the easiest thing would be to add a new array giving the reference track durations, indexed by the track IDs (just as HashTable.names is indexed by ID), and store it with the reference database.  At present, the code has no need for that value, so doesn't store it.
