### ISSUE TITLE
Shorter query question

### ISSUE THREAD

**Issue by fengliu2014** [dpwe/audfprint#25]
I was doing some test with the code.
The only difference is that now the query is 1s. To make it work, I increase the landmark density and change the target zone to a small one(63bins and 15 symbols). Even without noise and degradation, the recognition rate is just 92%. Is this expected? As the code is designed mainly for query 5sec at least?

**Comment by dpwe** [comment]
I think it takes on the order of seconds for the adaptive threshold to
settle. Perhaps a more sophisticated initialization scheme would give
better results on short examples.  What happens if you repeat the short
stimuli 2 or 3 times?

  DAn.

**Comment by fengliu2014** [comment]
Thank you DAn.
After repeat the stimuli, the recognition rate is better, 95%, but still not 100%.

By the way, does this algorithm only work when the training dataset contains the exact query audio?
I was trying to build a audio fingerprinting system for speech.
I have a dataset which consists of a lot of short speech audio(about 2s).
These audio files are generated by the same person. 
Then he speaks again and use this as query audio. In the training dataset, there are several files (>=10) that have same content as the query audio.
'Same content' means these audio files contain same words.
I am hopping to find one of them, but the performance is poor, about 20%.

**Comment by dpwe** [comment]
> By the way, does this algorithm only work when the training dataset contains the exact query audio?
> I was trying to build a audio fingerprinting system for speech.
> I have a dataset which consists of a lot of short speech audio(about 2s).
> These audio files are generated by the same person.
> Then he speaks again and use this as query audio. In the training dataset, there are several files (>=10) that have same content as the query audio.
> 'Same content' means these audio files contain same words.
> I am hoping to find one of them, but the performance is poor, about 20%.

Audio fingerprinting only matches exact instances (recordings) of waveforms.  Even when the same person repeats a word, there are slight differences in the frequencies and timing which alter the landmarks upon which the fingerprinting relies.
