### ISSUE TITLE
Accuracy against Noise

### ISSUE THREAD

**Issue by aldycool** [dpwe/audfprint#27]
Hi DAn,

Currently I'm testing the audfprint matching accuracy for mp3 song samples each with 60 seconds in length, against their own extracted parts of the audio with randomized starting position and varying lengths between 5 and 15 seconds, so that the matched audio is a part of the ingested audio which makes them identical in terms of their waveform. The tests went perfectly with 100% match. But then I've added some noise to into the randomize-extracted parts by merging noise sound with the clean ones. There are 3 type of noises, all of them are Brownian noise with 0.2 amplitude (low noise), 0.5 amplitude (medium) and 0.8 amplitude (high noise). The scale of amplitude noises is between 0 and 1. This test resulted in various results, but the bottom line is, the higher the noise, the probability of NOMATCH is increases.

To increase the accuracy against such tests (mixed with noises, even though they are identical), by your suggestion, what parameters should I tune? I'm afraid if I blindly test changing each of them, I may actually not know if I hit the right spot or not. I know there's a lot of them (--density, --pks-per-frame, etc), I also try to understand what each of them actually do, I'm getting there, but still needs to learn a lot :D. Thanks.

**Comment by dpwe** [comment]
You're on the right path.  I usually increase density first; I rarely see
benefits going above 100.  pks-per-frame and fanout are more experimental,
but you could try increasing them slowly to see what impact they have.

  DAn.
