### ISSUE TITLE
Test Audio

### ISSUE THREAD

**Issue by Cabalist** [dpwe/audfprint#31]
Hello,

I am looking at converting this to Python3.  I am looking over the tests and profiling but I can't seem to find any of the associated audio file.  Are they available?

**Comment by dpwe** [comment]
See the Matlab original at https://labrosa.ee.columbia.edu/matlab/audfprint/
You can get the reference files at https://labrosa.ee.columbia.edu/~dpwe/tmp/Nine_Lives/
and the query.mp3 file is within the zip package https://labrosa.ee.columbia.edu/matlab/audfprint/audfprint-v0.9.zip .  
or I just copied it to
https://labrosa.ee.columbia.edu/~dpwe/tmp/query.mp3

Sorry these are so well hidden!

  DAn.

**Comment by Cabalist** [comment]
Thanks!
