### ISSUE TITLE
Merging Tables With Different Hashbits

### ISSUE THREAD

**Issue by moishy90** [dpwe/audfprint#40]
Hi, 

I'm trying to merge tables with different number of hashbits. When I match against the original table it detects songs correctly, but when I match against the table that was merged with the original table it doesn't detect songs.

I don't really understand your implementation of the hash table, so if this operation doesn't make sense, please let me know. 

I'm doing this so that I can keep the size of the original hash table small. I'm storing many small pickled files in a database and merging those files into a hash table in memory when needed.

**Comment by dpwe** [comment]
It’s not possible to merge tables with different numbers of hash bits.  If
you're trying to work with reference files smaller than the default, you
could reduce --bucketsize from the default 100; I *think* you can merge
databases with different bucket sizes.

  DAn.

**Comment by moishy90** [comment]
OK. 

Excellent library. Thank you very much.
