### ISSUE TITLE
Concatenating precomuted hashes of consecutive parts of file

### ISSUE THREAD

**Issue by moishy90** [dpwe/audfprint#43]
Is there a way to concatenate precomputed hashes so that the times align properly?

I have recorded consecutive mp3 files and I precompute them. I would like to concatenate the precomputed files without needing to attach the original mp3 files and precomputing the attached file. 

I'm using your code as a library, so if you can share a code sample that would be great. 

I've tried offsetting the hash time by 430 for each file I add but it's not exact. even if I get the length of the original file using audio_read it's not exact.

**Comment by moishy90** [comment]
@dpwe this seems to be impossible considering that the info is lost when cutting the file

**Comment by dpwe** [comment]
I’m not completely sure what you’re asking. The hash representation stores
track IDs and time offset within the track, indexed by the landmark hash.
If you merge hash tables, each track is a separate entity. If the
individual tracks are actually segmented parts of a longer recording, you
could imagine post-processing that converts offsets within a segment to the
corresponding time in the unsegmented recording. I don’t think this
functionality belongs inside the fingerprint engine. But maybe you mean
something else?

  DAn.
