### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by branford19** [dpwe/audfprint#44]
Hi, having issues with recognising a clip using this script. 

**This is the command I used:**
python audfprint.py match --dbase db1.pklz SS9-18.wav

**And this is the traceback I get:**
Read fprints for 4864 files ( 25037164 hashes) from db1.pklz (2.75% dropped)
Traceback (most recent call last):
  File "audfprint.py", line 490, in <module>
    main(sys.argv)
  File "audfprint.py", line 473, in main
    strip_prefix=args['--wavdir'])
  File "audfprint.py", line 156, in do_cmd
    msgs = matcher.file_match_to_msgs(analyzer, hash_tab, filename, num)
  File "/home/ben/audio_recognition-master/bin/audfprint/audfprint_match.py", line 379, in file_match_to_msgs
    rslts, dur, nhash = self.match_file(analyzer, ht, qry, number)
  File "/home/ben/audio_recognition-master/bin/audfprint/audfprint_match.py", line 355, in match_file
    q_hashes = analyzer.wavfile2hashes(filename)
  File "/home/ben/audio_recognition-master/bin/audfprint/audfprint_analyze.py", line 407, in wavfile2hashes
    self.peaks2landmarks(peaklist)))
  File "/home/ben/audio_recognition-master/bin/audfprint/audfprint_analyze.py", line 89, in landmarks2hashes
    hashes[:, 0] = landmarks[:, 0]
IndexError: too many indices for array

Time is of the essence here unfortunately, and any help would be appreciated 😄

**Comment by dpwe** [comment]
It looks like no landmarks were created.  Is the file very short and/or
very quiet?

  DAn.

**Comment by dpwe** [comment]
0.4 s is going to be too short; a weakness of audfprint is that it takes
something like ~0.5 s to warm up from the start of a file.  Then the actual
landmark pairs need to be spread over several 100 ms.  So sounds with no
structure on that kind of timescale (e.g., a single transient) can't be
matched effectively.

You could try looping the sound say 5 times, which will at least give the
engine a chance to warm up and get landmarks on the event.  However, if
there's no substantial time structure for it to capture, it may still fail
to find matches.

Good luck,

  DAn.

**Comment by branford19** [comment]
I added 0.4s of white noise to the start and it worked! Thank you for your dedication to this code :)

**Comment by dpwe** [comment]
Oh! That’s great. Thanks for investigating and reporting back.

  DAn.
