### ISSUE TITLE
Gives varied results if computed vice versa

### ISSUE THREAD

**Issue by 2407adi** [dpwe/audfprint#49]
So I was dabbling with the implementation of the code wherein I was searching for a small audio clip(abc) into a larger recording(xyz).
When I pickle "abc" and the run the match command with "xyz" as the query, I revive perfect results, but the time detected is a total chaos when i do it vice versa; pickle xyz and match abc. 
Any idea why?
Thanks a ton!

**Comment by dpwe** [comment]
The times are stored modulo some maximum value; by default, this causes
times to "alias" when larger than 6 minutes; see the final paragraph of
https://github.com/dpwe/audfprint/blob/master/README.md

**Comment by 2407adi** [comment]
This totally works! Thanks a ton! 👍
