### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by jpweeks** [dpwe/audfprint#60]
Hello! I'd like to clarify the availability of this tool for use in commercial applications. I see it's licensed under MIT terms, but I'm not sure if the algorithms used are encumbered by intellectual rights patents, as they appear to be derived from research done by Shazam. Any insight here will be greatly appreciated!

Ps. Really excellent work on this project; it's been a really educational tool for me and was easy to get started with.

**Comment by dpwe** [comment]
I can’t give legal advice, but my implementation is based on the ideas in
Avery Wang’s paper.

  DAn.
