### ISSUE TITLE
Numpy Memory Error

### ISSUE THREAD

**Issue by Johndirr** [dpwe/audfprint#66]
When trying to build a database from an audio file thats about an hour long I get the following error:
```
File "C:\Temp\Python\audfprint-master\stft.py", line 93, in stft
    windowed_frames = frames * window
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (148776, 512) and data type float64
```
I tried this with an mp3 file and a wav (both have the same duration). It works fine for much shorter audio.
Is there anything I can do about this besides splitting the file?

PS. I'm on windows 10.

**Comment by Hellowlol** [comment]
Add more memory? 😂

**Comment by dpwe** [comment]
Splitting the audio is a good approach because matching is more efficient
when applied to shorter units (e.g. a couple of minutes). You can use
overlapping segments to avoid missing a match that spans a split.

  DAn.

**Comment by Johndirr** [comment]
> 
> 
> Add more memory? 😂

Tried it with 24 GB of free memory. Same error as before. Is this process really so demanding?

**Comment by Hellowlol** [comment]
How long is the audioclip?

**Comment by Johndirr** [comment]
About an hour.

**Comment by dpwe** [comment]
The original error message reports problems allocating a 148776 * 512 array
of float64, which sounds right for 1 hour of 23 ms frames (the default
frame duration). That corresponds to ~600MB by my calculation, which is a
lot of memory, but should be feasible on a machine with many GB of RAM.
Are you sure Python has access to the memory?  Perhaps
psutil.virtual_memory() can give useful information?

  DAn.

**Comment by Johndirr** [comment]
I searched for memory errors in genereal after you wrote about psutil. In the end the problem was a 32bit installation of Python. **It works with a 64bit installation of Python.**

Thank you for your time.
