### ISSUE TITLE
Incorrect time range

### ISSUE THREAD

**Issue by asimejaz14** [dpwe/audfprint#77]
Hey @dpwe First of all thanks for making my life so simpler. I am using this code for few days and its working all good except time range.

My input audio file **WAZOBIA.mp3** is 30 min long.

I tried your solutions which you provided on other issues, created new database with 18 bits and ran this command

`python audfprint -dbase testing.pklz WAZOBIA.mp3 --find-time-range --max-matches 20 --maxtimebits 18`

Incorrect results.

Again created a new database with default timebits and then ran the above command again with specifying maxtimebits to 18

but still starting time 9.52 min is correct but ending time is incorrect 0.50 min while it should be 10.02 min as the audio matched is just 10 sec (stored in database

Btw, I converted seconds to minutes just for my simplicity.
![wrong time](https://user-images.githubusercontent.com/59932222/74673623-643dae00-51d1-11ea-9656-de7ff3fe92de.PNG)

**Comment by dpwe** [comment]
The line reads:
"Matched 33.6 s
 starting at 9.52 min in WAZOBIA.mp3
 to time 0.50 min in audios/Airtel Smartalk.mp3 ..."

So it's saying the segment it matched was 33.6 s long (i.e., from 9:31 to
10:05 if I understand your unit conversion correctly).
The 0.50 min means that the portion it *matched* began at 0:30 in the
reference track "Airtel Smartalk.mp3".

I hope this clears it up, and you now consider this to be working correctly.

  DAn.
